import React,{useEffect,useState,createContext,useContext} from "react";
import {createRoot} from "react-dom/client";
import {BrowserRouter,Routes,Route,Link,NavLink,Navigate,Outlet,useNavigate} from "react-router-dom";
import {createClient} from "@supabase/supabase-js";
import "./style.css";

const URL=import.meta.env.VITE_SUPABASE_URL, KEY=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=URL&&KEY?createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}}):null;
async function fn(name,body){if(!supabase)throw Error("Supabase belum dikonfigurasi.");const {data,error}=await supabase.functions.invoke(name,{body});if(error)throw error;return data}
async function login(n,p){const r=await fn("login-member",{member_number:n,pin:p});if(r.access_token)await supabase.auth.setSession({access_token:r.access_token,refresh_token:r.refresh_token});return r}
async function logout(){if(supabase)await supabase.auth.signOut()}
async function verifyMember(n){const {data,error}=await supabase.rpc("verify_member",{p_member_number:n});if(error)throw error;return data}
async function events(){const {data,error}=await supabase.from("events").select("*").eq("status","published").order("event_date");if(error)throw error;return data||[]}
async function news(){const {data,error}=await supabase.from("news").select("*").eq("status","published").order("published_at",{ascending:false});if(error)throw error;return data||[]}
async function registerMember(x){const {data,error}=await supabase.from("member_registrations").insert(x).select().single();if(error)throw error;return data}

const A=createContext(null);
function Auth(){
 const [user,setUser]=useState(null),[session,setSession]=useState(null),[roles,setRoles]=useState([]),[loading,setLoading]=useState(true);
 async function refresh(){if(!supabase){setLoading(false);return}try{const {data}=await supabase.auth.getSession();setSession(data.session);setUser(data.session?.user||null);if(data.session){const r=await fn("get-member-roles");setRoles((r.roles||[]).map(x=>x.name||x))}}catch(e){console.error(e)}finally{setLoading(false)}}
 useEffect(()=>{refresh();if(!supabase)return;const {data:l}=supabase.auth.onAuthStateChange(()=>refresh());return()=>l.subscription.unsubscribe()},[]);
 return <A.Provider value={{user,session,roles,loading,refresh}}>{<Outlet/>}</A.Provider>
}
const useAuth=()=>useContext(A);

function Logo(){return <Link className="logo" to="/"><b>OMB</b><span>Ojol Molis Bersatu</span></Link>}
function Public({children=true}){return <><header><Logo/><nav>{[["/","Beranda"],["/profil","Profil"],["/agenda","Agenda"],["/berita","Berita"],["/benefit","Benefit"],["/mitra","Mitra"],["/cek-anggota","Cek Anggota"]].map(([p,t])=><NavLink end={p==="/"} to={p} key={p}>{t}</NavLink>)}</nav><Link className="btn green" to="/login">Masuk</Link></header><main>{children&&<Outlet/>}</main><footer>© {new Date().getFullYear()} OMB — Ojol Molis Bersatu</footer></>}
function Page({title,desc,children}){return <div className="page"><h1>{title}</h1>{desc&&<p className="muted">{desc}</p>}{children}</div>}
function Home(){return <section className="hero"><div><small>OJOL MOLIS BERSATU</small><h1>Satu platform untuk seluruh kebutuhan OMB.</h1><p>Website, keanggotaan, agenda, absensi, iuran, pembayaran, benefit, dan administrasi komunitas dalam satu sistem.</p><div className="actions"><Link className="btn green" to="/daftar">Daftar Anggota</Link><Link className="btn" to="/cek-anggota">Cek Anggota</Link></div></div><div className="heroBox"><b>OMB</b><h2>Ojol Molis Bersatu</h2><span>Integrated Membership Management System</span></div></section>}
function Simple({title,desc}){return <Page title={title} desc={desc}><div className="card empty">Konten dinamis akan dikelola melalui Supabase CMS.</div></Page>}
function Listing({type}){const [items,setItems]=useState([]),[busy,setBusy]=useState(true);useEffect(()=>{(type==="event"?events():news()).then(setItems).catch(console.error).finally(()=>setBusy(false))},[]);return <Page title={type==="event"?"Agenda OMB":"Berita OMB"} desc="Konten yang dipublikasikan admin.">{busy?<div className="card">Memuat...</div>:items.length?<div className="grid">{items.map(x=><article className="card" key={x.id}><small>{type==="event"?x.event_date:"BERITA"}</small><h2>{x.title}</h2><p>{x.description||x.excerpt||x.content?.slice(0,180)||"Detail akan ditampilkan di sini."}</p></article>)}</div>:<div className="card empty">Belum ada data.</div>}</Page>}
function Verify(){const [n,setN]=useState(""),[r,setR]=useState(null),[m,setM]=useState(""),[b,setB]=useState(false);async function go(e){e.preventDefault();setB(true);setR(null);setM("");try{const x=await verifyMember(n.trim().toUpperCase());x?setR(x):setM("Data anggota tidak ditemukan atau tidak aktif.")}catch(e){setM(e.message)}finally{setB(false)}}return <Page title="Cek Anggota" desc="Verifikasi status anggota OMB secara publik."><form className="card form" onSubmit={go}><label>Nomor Anggota<input required value={n} onChange={e=>setN(e.target.value)} placeholder="OMB-034"/></label><button className="btn green">{b?"Memeriksa...":"Cek Anggota"}</button>{m&&<div className="alert">{m}</div>}</form>{r&&<div className="card result"><small>ANGGOTA AKTIF</small><h2>{r.member_number}</h2><h3>{r.full_name}</h3><p>Nickname: {r.nickname||"-"}</p><p>Kendaraan: {[r.vehicle_brand,r.vehicle_model].filter(Boolean).join(" ")||"-"}</p><p>Aplikasi: {r.ojol_app||"-"}</p></div>}</Page>}
const fields=[["full_name","Nama lengkap"],["nickname","Nama panggilan"],["phone","WhatsApp aktif"],["city","Kota/Kabupaten domisili"],["vehicle_brand","Merek motor"],["vehicle_model","Model motor"],["vehicle_plate","Nomor polisi"]];
function Register(){const [f,setF]=useState(Object.fromEntries(fields.map(x=>[x[0],""]))),[ok,setOk]=useState(""),[b,setB]=useState(false);function s(k,v){setF({...f,[k]:v})}async function go(e){e.preventDefault();setB(true);try{const r=await registerMember({...f,registration_status:"pending",willing_to_join_events:true,agreed_to_rules:true});setOk("Pendaftaran diterima. ID registrasi: "+r.id)}catch(e){setOk(e.message)}finally{setB(false)}}return <Page title="Pendaftaran Anggota" desc="Isi data dasar terlebih dahulu. Data lain dapat dilengkapi setelah disetujui."><form className="card form grid2">{fields.map(([k,t])=><label key={k}>{t}<input required value={f[k]} onChange={e=>s(k,e.target.value)}/></label>)}<button className="btn green" disabled={b} onClick={go}>{b?"Mengirim...":"Kirim Pendaftaran"}</button>{ok&&<div className="alert">{ok}</div>}</form></Page>}
function Login(){const [n,setN]=useState(""),[p,setP]=useState(""),[m,setM]=useState(""),nav=useNavigate();async function go(e){e.preventDefault();setM("");try{const r=await login(n.trim().toUpperCase(),p);nav(r.must_change_pin?"/member/ganti-pin":"/member/dashboard")}catch(e){setM(e.message)}}return <div className="auth"><div className="authCard"><Logo/><h1>Masuk</h1><p className="muted">Nomor Anggota + PIN</p><form className="form"><label>Nomor Anggota<input required value={n} onChange={e=>setN(e.target.value)} placeholder="OMB-001"/></label><label>PIN<input required maxLength="6" inputMode="numeric" type="password" value={p} onChange={e=>setP(e.target.value.replace(/\D/g,"").slice(0,6))}/></label>{m&&<div className="alert error">{m}</div>}<button className="btn green">Masuk</button></form><Link to="/lupa-pin">Lupa PIN?</Link><Link to="/">← Website OMB</Link></div></div>}
function Guard({admin=false}){const {user,loading,roles}=useAuth();if(loading)return <div className="center">Memeriksa sesi...</div>;if(!user)return <Navigate to="/login" replace/>;if(admin&&!roles.some(r=>["super_admin","admin_membership","bendahara","admin_event","admin_content"].includes(r)))return <Navigate to="/member/dashboard" replace/>;return <App admin={admin}/>}

const member=["dashboard","profil","kartu","agenda","kehadiran","iuran","pembayaran","benefit"], admin=["dashboard","anggota","event","absensi","iuran","pembayaran","benefit","berita","agenda","mitra","pengurus","laporan","pengaturan"];
function App({admin=false}){const nav=admin?"/admin":"/member",items=admin?admin:member,{refresh}=useAuth();const labels={dashboard:"Dashboard",profil:"Profil Saya",kartu:"Kartu Anggota",agenda:"Agenda",kehadiran:"Kehadiran",iuran:"Iuran",pembayaran:"Pembayaran",benefit:"Benefit",anggota:"Anggota",event:"Event & Agenda",absensi:"Absensi",berita:"Berita",mitra:"Mitra",pengurus:"Pengurus",laporan:"Laporan",pengaturan:"Pengaturan"};return <div className="app"><aside><Logo/><small>{admin?"ADMINISTRASI":"MEMBER AREA"}</small>{items.map(x=><NavLink key={x} to={nav+"/"+x}>{labels[x]}</NavLink>)}<button className="btn dark" onClick={async()=>{await logout();await refresh()}}>Keluar</button></aside><section className="appmain"><Outlet/></section></div>}
function Dash({admin=false}){return <Page title={admin?"Dashboard Admin":"Dashboard Member"} desc="Ringkasan OMB V2."><div className="stats">{["Anggota aktif","Pendaftaran","Event","Tagihan"].map(x=><div className="card" key={x}><small>{x}</small><b>—</b></div>)}</div><div className="card"><h2>{admin?"Administrasi OMB":"Selamat datang di Member Area"}</h2><p>Data nyata akan tampil setelah terhubung dengan data Supabase. Tidak ada angka dummy.</p></div></Page>}
function Placeholder({name}){return <Page title={name} desc="Modul OMB V2"><div className="card empty">UI dasar sudah siap. CRUD dan detail modul akan kita kerjakan bertahap sesuai RLS dan permission Supabase.</div></Page>}
function Forgot(){const [n,setN]=useState(""),[otp,setO]=useState(""),[step,setStep]=useState(1),[m,setM]=useState("");async function req(e){e.preventDefault();try{const r=await fn("request-member-pin-recovery",{member_number:n.trim().toUpperCase()});setM(r.message||"Instruksi recovery diproses.");setStep(2)}catch(e){setM(e.message)}}async function ver(e){e.preventDefault();try{const r=await fn("verify-member-pin-recovery",{member_number:n.trim().toUpperCase(),otp});setM(r.message||"OTP terverifikasi. Langkah set PIN menyusul setelah backend recovery lengkap.")}catch(e){setM(e.message)}}return <div className="auth"><div className="authCard"><Logo/><h1>Lupa PIN</h1>{step===1?<form className="form" onSubmit={req}><label>Nomor Anggota<input required value={n} onChange={e=>setN(e.target.value)} placeholder="OMB-001"/></label><button className="btn green">Kirim OTP</button></form>:<form className="form" onSubmit={ver}><label>OTP 8 digit<input required maxLength="8" inputMode="numeric" value={otp} onChange={e=>setO(e.target.value.replace(/\D/g,""))}/></label><button className="btn green">Verifikasi OTP</button></form>}{m&&<div className="alert">{m}</div>}<Link to="/login">← Login</Link></div></div>}

function ChangePin(){const [p,setP]=useState(""),[c,setC]=useState(""),[m,setM]=useState(""),nav=useNavigate();async function go(e){e.preventDefault();if(!/^\d{6}$/.test(p)||p!==c)return setM("PIN harus 6 digit dan sama.");try{await fn("change-member-pin",{new_pin:p});nav("/member/dashboard")}catch(e){setM(e.message)}}return <Page title="Ganti PIN" desc="PIN awal wajib diganti."><form className="card form narrow"><label>PIN baru<input type="password" maxLength="6" inputMode="numeric" value={p} onChange={e=>setP(e.target.value.replace(/\D/g,""))}/></label><label>Konfirmasi PIN<input type="password" maxLength="6" inputMode="numeric" value={c} onChange={e=>setC(e.target.value.replace(/\D/g,""))}/></label>{m&&<div className="alert error">{m}</div>}<button className="btn green">Simpan PIN</button></form></Page>}

const memberNames={profil:"Profil Saya",kartu:"Kartu Anggota",agenda:"Agenda",kehadiran:"Kehadiran",iuran:"Iuran",pembayaran:"Pembayaran",benefit:"Benefit"};
const adminNames={anggota:"Anggota",event:"Event & Agenda",absensi:"Absensi",iuran:"Iuran",pembayaran:"Pembayaran",benefit:"Benefit",berita:"Berita",agenda:"Agenda",mitra:"Mitra",pengurus:"Pengurus",laporan:"Laporan",pengaturan:"Pengaturan"};
function RoutesApp(){return <Routes><Route element={<Auth/>}><Route element={<Public/>}><Route index element={<Home/>}/><Route path="profil" element={<Simple title="Profil OMB" desc="Informasi organisasi OMB."/>}/><Route path="agenda" element={<Listing type="event"/>}/><Route path="berita" element={<Listing type="news"/>}/><Route path="benefit" element={<Simple title="Benefit OMB" desc="Benefit anggota."/>}/><Route path="mitra" element={<Simple title="Mitra OMB" desc="Mitra dan kerja sama."/>}/><Route path="cek-anggota" element={<Verify/>}/><Route path="daftar" element={<Register/>}/></Route><Route path="login" element={<Login/>}/><Route path="lupa-pin" element={<Forgot/>}/><Route path="member/ganti-pin" element={<Guard/><ChangePin/>}/><Route path="member" element={<Guard/>}><Route element={<App/>}><Route path="dashboard" element={<Dash/>}/>{Object.entries(memberNames).map(([k,v])=><Route key={k} path={k} element={<Placeholder name={v}/>}/>)}</Route></Route><Route path="admin" element={<Guard admin/>}><Route element={<App admin/>}><Route path="dashboard" element={<Dash admin/>}/>{Object.entries(adminNames).map(([k,v])=><Route key={k} path={k} element={<Placeholder name={v}/>}/>)}</Route></Route><Route path="*" element={<Navigate to="/" replace/>}/></Route></Routes>}

createRoot(document.getElementById("root")).render(<BrowserRouter><RoutesApp/></BrowserRouter>);
